spring.application.name=sky1



spring.datasource.url=jdbc:mysql://localhost:3306/sky
spring.datasource.username=root
spring.datasource.password=20040729aA

mybatis.check-config-location=false
mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.type-aliases-package=cn.whpu.sky1.dto
mybatis.configuration.map-underscore-to-camel-case=true
