spring.application.name=sky1

spring.config.import=classpath:application-prod.yml
# MySQL ???????
spring.datasource.url=${db.url}
spring.datasource.username=${db.username}
spring.datasource.password=${db.password}
spring.datasource.driver-class-name=${db.driver}


# MyBatis ??
mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.type-aliases-package=cn.whpu.sky1.entity
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl

# ????
logging.level.cn.whpu.sky1.mapper=debug
logging.level.cn.whpu.sky1.service=debug
